name: Master workflow

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.0

    - name: Setup project
      run: make install

    - name: Check lint
      run: make lint
